version: "3.8"

services:
  deckgl:
    build:
      context: ./deckgl
      dockerfile: Dockerfile
    container_name: deckgl_frontend
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      # src 폴더 마운트 (Map.tsx 수정 시 핫리로드)
      - ./deckgl/src:/app/src
    environment:
      - VITE_TEGOLA_URL=http://localhost:28080

